#!/bin/sh
fail() {
    echo GCC_CENTOS7_KERNEL_FAIL
    poweroff -f
    sleep 1000
}
trap fail EXIT
set -eu
export PATH=/bin
export HOME=/root
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
exec </dev/console >/dev/console 2>&1
uname -r | grep -q '^3\.10\.0-1160\.el7\.x86_64$'
uname -a
sh /gcc-smoke.sh
echo GCC_CENTOS7_KERNEL_PASS
trap - EXIT
poweroff -f
